import React from 'react';
import Head from 'next/head';

const Home = () => {
  return (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
        </Head>

        <main>
            <h1>Olá!</h1>
        </main>

    </div>
  )
}

export default Home;
